name: simple ci/cd
on:
  push:
    branches: 
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Run this command
        run: echo "Welcome to my simple CI/CD GitHub Actions pipeline"
